version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pw

  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v2.31.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:pw@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## enable experimental features.
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: inherited_roles
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_ADMIN_SECRET
      HASURA_GRAPHQL_JWT_SECRET: $HASURA_GRAPHQL_JWT_SECRET

  go-server:
    container_name: go-server
    build:
      dockerfile: $PWD/go-server/Dockerfile.local
    ports:
      - '4001:4001'
    restart: always
    environment:
      PORT: 4001

volumes:
  db-data:
