-- name: UpsertCharacterStats :exec
INSERT INTO character_stats (
        character_id,
        main_skill,
        combined_dps,
        total_dps,
        full_dps,
        total_dot_dps,
        life,
        life_unreserved,
        energy_shield,
        mana,
        ward,
        total_ehp,
        armour,
        evasion,
        block_chance,
        spell_block_chance,
        spell_suppression_chance,
        fire_resist,
        cold_resist,
        lightning_resist,
        chaos_resist,
        crit_chance,
        crit_multiplier,
        attack_speed
    )
VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
    ) ON CONFLICT (character_id) DO
UPDATE
SET main_skill = EXCLUDED.main_skill,
    combined_dps = EXCLUDED.combined_dps,
    total_dps = EXCLUDED.total_dps,
    full_dps = EXCLUDED.full_dps,
    total_dot_dps = EXCLUDED.total_dot_dps,
    life = EXCLUDED.life,
    life_unreserved = EXCLUDED.life_unreserved,
    energy_shield = EXCLUDED.energy_shield,
    mana = EXCLUDED.mana,
    ward = EXCLUDED.ward,
    total_ehp = EXCLUDED.total_ehp,
    armour = EXCLUDED.armour,
    evasion = EXCLUDED.evasion,
    block_chance = EXCLUDED.block_chance,
    spell_block_chance = EXCLUDED.spell_block_chance,
    spell_suppression_chance = EXCLUDED.spell_suppression_chance,
    fire_resist = EXCLUDED.fire_resist,
    cold_resist = EXCLUDED.cold_resist,
    lightning_resist = EXCLUDED.lightning_resist,
    chaos_resist = EXCLUDED.chaos_resist,
    crit_chance = EXCLUDED.crit_chance,
    crit_multiplier = EXCLUDED.crit_multiplier,
    attack_speed = EXCLUDED.attack_speed;
