-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO public.league_type (value) VALUES ('settlers_of_kalguur') ON CONFLICT DO NOTHING;
