// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-configured-league.sql

package smoldata

import (
	"context"
)

const getConfiguredLeague = `-- name: GetConfiguredLeague :one
SELECT league_name
FROM app_config
WHERE id = 1
`

func (q *Queries) GetConfiguredLeague(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfiguredLeague)
	var league_name string
	err := row.Scan(&league_name)
	return league_name, err
}
