// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package smoldata

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Character struct {
	Rank           int32
	PoeAccountName string
	Name           string
	Class          string
	Level          int32
	Experience     int64
	Retired        bool
	Dead           bool
	ID             string
	Challenges     int32
	Twitch         sql.NullString
}

type HdbCatalogHdbActionLog struct {
	ID                 uuid.UUID
	ActionName         sql.NullString
	InputPayload       json.RawMessage
	RequestHeaders     json.RawMessage
	SessionVariables   json.RawMessage
	ResponsePayload    pqtype.NullRawMessage
	Errors             pqtype.NullRawMessage
	CreatedAt          time.Time
	ResponseReceivedAt sql.NullTime
	Status             string
}

type HdbCatalogHdbCronEvent struct {
	ID            string
	TriggerName   string
	ScheduledTime time.Time
	Status        string
	Tries         int32
	CreatedAt     sql.NullTime
	NextRetryAt   sql.NullTime
}

type HdbCatalogHdbCronEventInvocationLog struct {
	ID        string
	EventID   sql.NullString
	Status    sql.NullInt32
	Request   pqtype.NullRawMessage
	Response  pqtype.NullRawMessage
	CreatedAt sql.NullTime
}

type HdbCatalogHdbMetadatum struct {
	ID              int32
	Metadata        json.RawMessage
	ResourceVersion int32
}

type HdbCatalogHdbScheduledEvent struct {
	ID            string
	WebhookConf   json.RawMessage
	ScheduledTime time.Time
	RetryConf     pqtype.NullRawMessage
	Payload       pqtype.NullRawMessage
	HeaderConf    pqtype.NullRawMessage
	Status        string
	Tries         int32
	CreatedAt     sql.NullTime
	NextRetryAt   sql.NullTime
	Comment       sql.NullString
}

type HdbCatalogHdbScheduledEventInvocationLog struct {
	ID        string
	EventID   sql.NullString
	Status    sql.NullInt32
	Request   pqtype.NullRawMessage
	Response  pqtype.NullRawMessage
	CreatedAt sql.NullTime
}

type HdbCatalogHdbSchemaNotification struct {
	ID              int32
	Notification    json.RawMessage
	ResourceVersion int32
	InstanceID      uuid.UUID
	UpdatedAt       sql.NullTime
}

type HdbCatalogHdbVersion struct {
	HasuraUuid     uuid.UUID
	Version        string
	UpgradedOn     time.Time
	CliState       json.RawMessage
	ConsoleState   json.RawMessage
	EeClientID     sql.NullString
	EeClientSecret sql.NullString
}

type ItemOrderType struct {
	Value string
}

type League struct {
	ID          string
	Realm       string
	Url         sql.NullString
	StartAt     time.Time
	EndAt       time.Time
	Description sql.NullString
	CategoryID  sql.NullString
	RegisterAt  time.Time
	DelveEvent  bool
}

type LeagueCategory struct {
	ID      string
	Current bool
}

type LeagueRule struct {
	ID          string
	Name        string
	Description sql.NullString
	LeagueID    sql.NullString
}

type LeagueType struct {
	Value string
}

type User struct {
	ID            uuid.UUID
	DiscordUserID sql.NullString
	DiscordName   sql.NullString
	PoeUserID     sql.NullString
	PoeName       sql.NullString
	DiscordAvatar sql.NullString
	Guild         sql.NullString
}

type UserItemOrder struct {
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ID           uuid.UUID
	UserID       uuid.UUID
	Description  sql.NullString
	LinkUrl      sql.NullString
	FulfilledBy  uuid.NullUUID
	Type         string
	Priority     bool
	ItemBaseType sql.NullString
	IconUrl      sql.NullString
	ItemCategory sql.NullString
}

type UserLeagueMechanic struct {
	ID       uuid.UUID
	Mechanic string
	UserID   uuid.UUID
}
