// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert-character-stats.sql

package smoldata

import (
	"context"
	"database/sql"
)

const upsertCharacterStats = `-- name: UpsertCharacterStats :exec
INSERT INTO character_stats (
        character_id,
        main_skill,
        combined_dps,
        total_dps,
        full_dps,
        total_dot_dps,
        life,
        life_unreserved,
        energy_shield,
        mana,
        ward,
        total_ehp,
        armour,
        evasion,
        block_chance,
        spell_block_chance,
        spell_suppression_chance,
        fire_resist,
        cold_resist,
        lightning_resist,
        chaos_resist,
        crit_chance,
        crit_multiplier,
        attack_speed
    )
VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
    ) ON CONFLICT (character_id) DO
UPDATE
SET main_skill = EXCLUDED.main_skill,
    combined_dps = EXCLUDED.combined_dps,
    total_dps = EXCLUDED.total_dps,
    full_dps = EXCLUDED.full_dps,
    total_dot_dps = EXCLUDED.total_dot_dps,
    life = EXCLUDED.life,
    life_unreserved = EXCLUDED.life_unreserved,
    energy_shield = EXCLUDED.energy_shield,
    mana = EXCLUDED.mana,
    ward = EXCLUDED.ward,
    total_ehp = EXCLUDED.total_ehp,
    armour = EXCLUDED.armour,
    evasion = EXCLUDED.evasion,
    block_chance = EXCLUDED.block_chance,
    spell_block_chance = EXCLUDED.spell_block_chance,
    spell_suppression_chance = EXCLUDED.spell_suppression_chance,
    fire_resist = EXCLUDED.fire_resist,
    cold_resist = EXCLUDED.cold_resist,
    lightning_resist = EXCLUDED.lightning_resist,
    chaos_resist = EXCLUDED.chaos_resist,
    crit_chance = EXCLUDED.crit_chance,
    crit_multiplier = EXCLUDED.crit_multiplier,
    attack_speed = EXCLUDED.attack_speed
`

type UpsertCharacterStatsParams struct {
	CharacterID            string
	MainSkill              sql.NullString
	CombinedDps            float64
	TotalDps               float64
	FullDps                float64
	TotalDotDps            float64
	Life                   float64
	LifeUnreserved         float64
	EnergyShield           float64
	Mana                   float64
	Ward                   float64
	TotalEhp               float64
	Armour                 float64
	Evasion                float64
	BlockChance            float64
	SpellBlockChance       float64
	SpellSuppressionChance float64
	FireResist             float64
	ColdResist             float64
	LightningResist        float64
	ChaosResist            float64
	CritChance             float64
	CritMultiplier         float64
	AttackSpeed            float64
}

func (q *Queries) UpsertCharacterStats(ctx context.Context, arg UpsertCharacterStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacterStats,
		arg.CharacterID,
		arg.MainSkill,
		arg.CombinedDps,
		arg.TotalDps,
		arg.FullDps,
		arg.TotalDotDps,
		arg.Life,
		arg.LifeUnreserved,
		arg.EnergyShield,
		arg.Mana,
		arg.Ward,
		arg.TotalEhp,
		arg.Armour,
		arg.Evasion,
		arg.BlockChance,
		arg.SpellBlockChance,
		arg.SpellSuppressionChance,
		arg.FireResist,
		arg.ColdResist,
		arg.LightningResist,
		arg.ChaosResist,
		arg.CritChance,
		arg.CritMultiplier,
		arg.AttackSpeed,
	)
	return err
}
