# fly.toml app configuration file generated for smol-hasura on 2023-08-12T09:34:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smol-hasura"
primary_region = "lhr"

[build]
  image = "hasura/graphql-engine:v2.31.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
